name: Deploy to DockerHub 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Push to Docker Hub 
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clona el código
      - uses: actions/checkout@v3

      # Paso 2: Configura Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Paso 4: Build + Push a Docker Hub
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pruebaprogra:latest
